---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox
spec:
  limits:
    - type: Pod
      max:
        cpu: 2000m
        memory: 4096Mi
    - type: Container
      default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox
spec:
  hard:
    cpu: "8"
    memory: 8Gi
    pods: "16"
