apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonplattner/k8s-sandbox
    path: src/gitops/cluster-config
    targetRevision: {{ .Values.targetRevision }}
  destination:
    name: in-cluster
    namespace: gitops
