apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-sandbox
  source:
    repoURL: https://github.com/simonplattner/k8s-sandbox
    path: src/gitops/argo-cd
    targetRevision: {{ .Values.targetRevision }}
  destination:
    name: in-cluster
    namespace: gitops
